
import re
if __name__ == "__main__":

    remote = """
    
    insert into v_ewell_inpatients (PATIENT_ID, SERIES, MRN, DISPLAY_ID, BED_NO, NAME, PHYSI_SEX_CODE, BIRTH_DATE, AGE, WEIGHT, HEIGHT, OCCUPATION_CATEG_CODE, OCCUPATION_CATEG_NAME, CONTACT_INFO, CONTACT_NUMBER, ADDRESS, WARD_CODE, WARD_NAME, DEPT_CODE, DEPT_NAME, ADMISSION_TIME, ADMISSION_WARD_TIME, DISCHARGE_TIME, DIAGNOSIS_NAME, DIAGNOSIS_NAME1, NURSING_CLASS, PATIENT_PATHOGENETIC_CONDITION, CHARGE_TYPE_CODE, CHARGE_TYPE_NAME, TOTAL_COST, PRE_PAYMENT, SELF_PAYMENT, BALANCE, ARREAR_FLAG, DIET, ALLERGY, ATTEND_DR_NAME, STATUS, IS_PRE_OUT, IDCODE, NURSE, NATION_CODE, COUN_CODE, MARI)
    """
    remoteColumns = []
    for i in remote.split("\n"):
        if "insert" in i:
            columns = re.findall("\((.*)\)", i)
            for column in columns[0].split(", "):
                # print(column)
                remoteColumns.append(column)


    remoteDDL = """
  `PAT_INDEX_NO` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `ADMISSION_DEPT_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADMISSION_DEPT_NAME` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADMISSION_REASON` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADMISSION_TIME` datetime(0) NOT NULL,
  `ADMISSION_WARD_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADMISSION_WARD_NAME` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADMISSION_WARD_TIME` datetime(0) NULL DEFAULT NULL,
  `ADMIT_SITUATION` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADMIT_WAY_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADMIT_WAY_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ALLERGY` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ARREAR_FLAG` int(11) NULL DEFAULT NULL,
  `ATTEND_DR_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ATTEND_DR_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `BALANCE` decimal(12, 2) NULL DEFAULT NULL,
  `BED_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `BIRTH_DATE` datetime(0) NULL DEFAULT NULL,
  `BRIEF_DISEASE_SITUATION` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CHARGE_TYPE_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CHARGE_TYPE_NAME` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CHIEF_DR_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CHIEF_DR_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CREATE_TIME` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
  `CURR_DISEASE_HISTORY` varchar(101) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DEPT_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DEPT_NAME` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DIAGNOSIS` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `DIAGNOSIS_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DIAGNOSIS_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DIET` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DISCHARGE_DATE` datetime(0) NULL DEFAULT NULL,
  `DISCHARGE_DIAG_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DISCHARGE_DIAG_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DISCHARGE_METHOD_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DISCHARGE_METHOD_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DISCHARGE_STATUS` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DISCHARGE_TIME` datetime(0) NULL DEFAULT NULL,
  `DISEASE_HISTORY` varchar(102) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DISEASES_REPORTED_FLAG` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ID_NUMBER` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INFECT_DISEASE_HISTORY` varchar(105) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INHOSP_DR_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `INHOSP_DR_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LEAVE_HOSPITAL_DEPT_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LEAVE_HOSPITAL_DEPT_NAME` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LEAVE_HOSPITAL_WARD_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LEAVE_HOSPITAL_WARD_NAME` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `METACHYSIS_HISTORY` varchar(104) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `MOBILE_NO` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `MRN` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `NAME` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `NURSING_CLASS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ORGAN_CODE` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `OUTCOME_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `OUTCOME_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PAT_CHIEF_DESCR` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PATIENT_ID` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `PATIENT_PATHOGENETIC_CONDITION` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PHYSI_SEX_CODE` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PHYSI_SEX_NAME` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PHYSICAL_EXAM` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PRE_PAYMENT` decimal(12, 2) NULL DEFAULT NULL,
  `RECEPT_TREAT_DR_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `RECEPT_TREAT_DR_NAME` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SELF_PAYMENT` decimal(12, 2) NULL DEFAULT NULL,
  `SERIES` int(11) NOT NULL,
  `SICKROOM_NO` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `STATUS` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `SURGERY_HISTORY` varchar(103) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `TOTAL_COST` decimal(12, 2) NULL DEFAULT NULL,
  `TREAT_PROCESS_DESCR` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `TREATMENT_ADVICE` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `UPDATE_TIME` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0),
  `VISIT_CARD_NO` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `WARD_CODE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `WARD_NAME` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `BED_SORT` int(11) NULL DEFAULT NULL,
  `NURSING_CLASS_SORT` int(11) NULL DEFAULT NULL,
  `SEX_SORT` int(11) NULL DEFAULT NULL,
  `PRIMARY_NURSE_CODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任护士工号',
  `PRIMARY_NURSE_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任护士姓名',
  `PRIMARY_HEAD_NURSE_CODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任护士长工号',
  `PRIMARY_HEAD_NURSE_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任护士长姓名',
  `CRITICAL_LEVEL` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '危重级别： 病危 病重',
  `PRE_LEAVE_HOSPITAL_TIME` timestamp(0) NULL DEFAULT NULL COMMENT '预出院时间',
  `AGE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `WEIGHT` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `HEIGHT` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NATION_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NATION_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ETHNIC_CODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ETHNIC_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `MARITAL_STATUS_CODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `MARITAL_STATUS_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CERTIFICATE_TYPE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CERTIFICATE_NO` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `EDUCATION_CODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `EDUCATION_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `OCCUPATION_CATEG_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `OCCUPATION_CATEG_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_INFO` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_NUMBER` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_ADDR` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `POSTALCODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADDRESS` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `HOMEPHONE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `HUKOU_ADDR` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `NATIVE_ADDR` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `EMAIL` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COMPANY` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ADDR_COMPANY` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COMPANY_PHONE_NO` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_RELATION_CODE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_RELATION_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COMPANY_CERTIFICATE_TYPE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `COMPANY_CERTIFICATE_NO` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_PERSON_ADDR` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CONTACT_PHONE_NO` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `PHONE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `EXT_PATIENT_ID` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ARCHIVED_STATUS` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `CLINICAL_PATHWAY` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `WRIST_BAND` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    """

    remoteDDLColumns = []
    for i in remoteDDL.split("\n"):
        if i != "":
            column = i.split(" ")[2].replace("`", "")
            # print(column)
            remoteDDLColumns.append(column)

    with open("model.java", "r", encoding="utf-8") as f:
        source = f.read()

    for i in source.split("\n"):
        if i.startswith("	@Column("):
            column = i.replace("\t@Column(name = \"", "").replace("\")", "")
            # print(column)
            # if column not in remoteColumns:
            if column not in remoteDDLColumns:
                print(column)

